import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const publicaSans = localFont({
  variable: "--font-publica-sans",
  src: "../public/fonts/ZPublicaSans.otf",
  weight: "400",
  style: "normal",
});

const publicaSansMedium = localFont({
  variable: "--font-publica-sans-medium",
  src: "../public/fonts/PublicaSans-Medium.otf",
  weight: "500",
  style: "normal",
});

const publicaSansBold = localFont({
  variable: "--font-publica-sans-bold",
  src: "../public/fonts/PublicaSans-Bold.otf",
  weight: "700",
  style: "normal",
});

const publicaSansExtraBold = localFont({
  variable: "--font-publica-sans-extra-bold",
  src: "../public/fonts/PublicaSans-ExtraBold.otf",
  weight: "800",
  style: "normal",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${publicaSans.variable} ${publicaSansMedium.variable} ${publicaSansBold.variable} ${publicaSansExtraBold.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
